import { useEffect, useMemo, useRef, useState } from 'react'
import { Routes, Route, Link, useNavigate, useParams } from 'react-router-dom'
import { supabase } from './supabase'

const COLORS = [
  { solid: '#d85b66', soft: 'rgba(216,91,102,.18)' }, { solid: '#4f7cff', soft: 'rgba(79,124,255,.18)' },
  { solid: '#31a27c', soft: 'rgba(49,162,124,.18)' }, { solid: '#d08a2f', soft: 'rgba(208,138,47,.18)' },
  { solid: '#8a63d2', soft: 'rgba(138,99,210,.18)' }, { solid: '#d05fa8', soft: 'rgba(208,95,168,.18)' },
  { solid: '#2f9db1', soft: 'rgba(47,157,177,.18)' }, { solid: '#7a9852', soft: 'rgba(122,152,82,.18)' },
]
const participantKey = (code) => `food-decider-participant-${code}`
const shorten = (value, max = 50) => { const text = String(value ?? '').trim(); return text.length <= max ? text : `${text.slice(0, max - 1)}...` }

function ThemeToggle() {
  const [theme, setTheme] = useState(() => localStorage.getItem('food-decider-theme') || 'light')
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem('food-decider-theme', theme) }, [theme])
  return <div className="theme-toggle" role="group" aria-label="Theme selection"><button type="button" className={theme === 'light' ? 'theme-button active' : 'theme-button'} onClick={() => setTheme('light')}>☀ Light</button><button type="button" className={theme === 'dark' ? 'theme-button active' : 'theme-button'} onClick={() => setTheme('dark')}>☾ Dark</button></div>
}
function Layout({ children }) { return <><ThemeToggle />{children}</> }
function generateCode() { const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; return Array.from({ length: 6 }, () => chars[Math.floor(Math.random() * chars.length)]).join('') }

function HomePage() {
  const navigate = useNavigate(); const [code, setCode] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  async function createRoom() { setBusy(true); setError(''); try { let room = null; for (let i = 0; i < 5 && !room; i += 1) { const result = await supabase.from('rooms').insert({ code: generateCode() }).select().single(); if (!result.error) room = result.data } if (!room) throw new Error('Could not create room.'); navigate(`/room/${room.code}`) } catch (err) { setError(err.message || 'Something went wrong.') } finally { setBusy(false) } }
  return <Layout><div className="app-shell"><div className="card hero-card app-title-card"><h1>Pick a place without the group chat chaos.</h1><p className="subtext">Create a room, share the code, add options, and drag your 100 points toward what you actually want to eat.</p><div className="actions"><button className="btn btn-primary" onClick={createRoom} disabled={busy}>{busy ? 'Creating...' : 'Create room'}</button></div><form className="join-form" onSubmit={(event) => { event.preventDefault(); const value = code.trim().toUpperCase(); if (value) navigate(`/room/${value}`) }}><div className="join-row"><input className="input" value={code} onChange={(event) => setCode(event.target.value.toUpperCase())} maxLength={6} placeholder="Join with room code" /><button className="btn btn-secondary" type="submit">Join</button></div></form>{error ? <p className="error-text">{error}</p> : null}</div></div></Layout>
}

function NamePage() {
  const { code } = useParams(); const navigate = useNavigate(); const upper = code.toUpperCase(); const [room, setRoom] = useState(null); const [name, setName] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(true)
  useEffect(() => { let active = true; supabase.from('rooms').select().eq('code', upper).maybeSingle().then(({ data, error: queryError }) => { if (!active) return; if (queryError) setError(queryError.message); else if (!data) setError('Room not found.'); else setRoom(data); setBusy(false) }); return () => { active = false } }, [upper])
  async function submit(event) { event.preventDefault(); const trimmed = name.trim(); if (!trimmed || !room) return; setBusy(true); setError(''); try { const duplicate = await supabase.from('participants').select('id').eq('room_id', room.id).eq('display_name', trimmed).maybeSingle(); if (duplicate.error) throw duplicate.error; if (duplicate.data) throw new Error('That name is already taken.'); const result = await supabase.from('participants').insert({ room_id: room.id, display_name: trimmed }).select().single(); if (result.error) throw result.error; localStorage.setItem(participantKey(upper), result.data.id); await supabase.from('messages').insert({ room_id: room.id, participant_id: result.data.id, type: 'system', body: '', meta: { kind: 'join', name: trimmed } }); navigate(`/room/${upper}`, { replace: true }) } catch (err) { setError(err.message || 'Could not join room.') } finally { setBusy(false) } }
  return <Layout><div className="app-shell"><div className="card hero-card"><Link to="/" className="back-link">Back</Link>{error && !room ? <><h2>Couldn’t open room</h2><p className="error-text">{error}</p></> : <><h2>What should we call you?</h2><p className="subtext small">Choose the name other people in this room will see.</p><form className="stack-form" onSubmit={submit}><div className="join-row"><input className="input" value={name} onChange={(event) => setName(event.target.value)} maxLength={60} placeholder="Your name" autoFocus /><button className="btn btn-primary" disabled={busy} type="submit">{busy ? 'Joining...' : 'Join room'}</button></div></form>{error ? <p className="error-text">{error}</p> : null}</>}</div></div></Layout>
}

function RoomPage() {
  const { code } = useParams(); const navigate = useNavigate(); const upper = code.toUpperCase()
  const [room, setRoom] = useState(null); const [me, setMe] = useState(null); const [participants, setParticipants] = useState([]); const [suggestions, setSuggestions] = useState([]); const [votes, setVotes] = useState([]); const [draft, setDraft] = useState({}); const [messages, setMessages] = useState([]); const [suggestion, setSuggestion] = useState(''); const [chat, setChat] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [removed, setRemoved] = useState(false); const [kickTarget, setKickTarget] = useState(null); const [kicking, setKicking] = useState(false); const [saving, setSaving] = useState(false); const [copyMessage, setCopyMessage] = useState('')
  const chatRef = useRef(null); const saveTimer = useRef(null); const removalTimer = useRef(null); const hydratingRef = useRef(false)

  async function refresh(roomId) { const [p, s, v, m] = await Promise.all([supabase.from('participants').select().eq('room_id', roomId).order('created_at'), supabase.from('suggestions').select().eq('room_id', roomId).order('created_at'), supabase.from('votes').select().eq('room_id', roomId), supabase.from('messages').select().eq('room_id', roomId).order('created_at').limit(80)]); if (p.error) throw p.error; if (s.error) throw s.error; if (v.error) throw v.error; if (m.error) throw m.error; setParticipants(p.data || []); setSuggestions(s.data || []); setVotes(v.data || []); setMessages(m.data || []) }
  function showRemoved() { setRemoved(true); localStorage.removeItem(participantKey(upper)); clearTimeout(removalTimer.current); removalTimer.current = window.setTimeout(() => navigate('/', { replace: true }), 5000) }

  useEffect(() => { let active = true; (async () => { try { const result = await supabase.from('rooms').select().eq('code', upper).maybeSingle(); if (result.error) throw result.error; if (!result.data) throw new Error('Room not found.'); if (!active) return; setRoom(result.data); const storedId = localStorage.getItem(participantKey(upper)); if (!storedId) { navigate(`/room/${upper}/name`, { replace: true }); return } const participant = await supabase.from('participants').select().eq('id', storedId).eq('room_id', result.data.id).maybeSingle(); if (!participant.data) { localStorage.removeItem(participantKey(upper)); navigate(`/room/${upper}/name`, { replace: true }); return } setMe(participant.data); await refresh(result.data.id) } catch (err) { if (active) setError(err.message || 'Could not open room.') } finally { if (active) setLoading(false) } })(); return () => { active = false } }, [upper, navigate])

  useEffect(() => {
    if (!me?.id || !suggestions.length) return
    hydratingRef.current = true
    setDraft((current) => {
      const next = {}
      const activeIds = new Set(suggestions.map((item) => item.id))
      votes.forEach((vote) => { if (vote.participant_id === me.id && activeIds.has(vote.suggestion_id)) next[vote.suggestion_id] = vote.points })
      suggestions.forEach((item) => { if (next[item.id] === undefined && current[item.id] !== undefined) next[item.id] = current[item.id] })
      suggestions.forEach((item) => { if (next[item.id] === undefined) next[item.id] = 0 })
      return next
    })
    queueMicrotask(() => { hydratingRef.current = false })
  }, [me?.id, votes, suggestions])

  useEffect(() => { if (!room?.id) return undefined; const channel = supabase.channel(`room-${room.id}`).on('postgres_changes', { event: '*', schema: 'public', table: 'participants', filter: `room_id=eq.${room.id}` }, (payload) => { if (payload.eventType === 'DELETE') { setParticipants((current) => current.filter((item) => item.id !== payload.old?.id)); setVotes((current) => current.filter((vote) => vote.participant_id !== payload.old?.id)); if (payload.old?.id === me?.id) showRemoved() } else if (payload.new) setParticipants((current) => [...current.filter((item) => item.id !== payload.new.id), payload.new]) }).on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'kicks', filter: `room_id=eq.${room.id}` }, (payload) => { const id = payload.new?.participant_id; if (!id) return; setParticipants((current) => current.filter((item) => item.id !== id)); setVotes((current) => current.filter((vote) => vote.participant_id !== id)); if (id === me?.id) showRemoved() }).on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'messages', filter: `room_id=eq.${room.id}` }, (payload) => setMessages((current) => [...current, payload.new].slice(-80))).on('postgres_changes', { event: '*', schema: 'public', table: 'votes', filter: `room_id=eq.${room.id}` }, () => refresh(room.id).catch(() => {})).on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'suggestions', filter: `room_id=eq.${room.id}` }, (payload) => setSuggestions((current) => [...current.filter((item) => item.id !== payload.new.id), payload.new])).on('postgres_changes', { event: 'DELETE', schema: 'public', table: 'suggestions' }, (payload) => { const id = payload.old?.id; setSuggestions((current) => current.filter((item) => item.id !== id)); setVotes((current) => current.filter((vote) => vote.suggestion_id !== id)); setDraft((current) => { const next = { ...current }; delete next[id]; return next }) }).subscribe(); return () => { supabase.removeChannel(channel); clearTimeout(removalTimer.current); clearTimeout(saveTimer.current) } }, [room?.id, me?.id, upper, navigate])
  useEffect(() => { if (chatRef.current) chatRef.current.scrollTop = chatRef.current.scrollHeight }, [messages])

  const colored = useMemo(() => participants.map((person, index) => ({ ...person, color: COLORS[index % COLORS.length] })), [participants])
  const meColor = colored.find((person) => person.id === me?.id)?.color || COLORS[0]
  const used = Object.values(draft).reduce((sum, value) => sum + value, 0)
  const optimistic = useMemo(() => { const mine = votes.filter((vote) => vote.participant_id === me?.id); const others = votes.filter((vote) => vote.participant_id !== me?.id); const mineForDisplay = suggestions.map((item) => ({ participant_id: me?.id, suggestion_id: item.id, points: draft[item.id] ?? mine.find((vote) => vote.suggestion_id === item.id)?.points ?? 0 })); return [...others, ...mineForDisplay] }, [votes, me?.id, suggestions, draft])
  const totals = useMemo(() => { const result = {}; suggestions.forEach((item) => { result[item.id] = 0 }); optimistic.forEach((vote) => { result[vote.suggestion_id] = (result[vote.suggestion_id] || 0) + vote.points }); return result }, [suggestions, optimistic])
  const sorted = useMemo(() => [...suggestions].sort((a, b) => (totals[b.id] || 0) - (totals[a.id] || 0) || a.created_at.localeCompare(b.created_at)), [suggestions, totals])
  const top = sorted.slice(0, 3); const maxTotal = Math.max(1, ...top.map((item) => totals[item.id] || 0))
  const pointsLeft = colored.map((person) => { const spent = optimistic.filter((vote) => vote.participant_id === person.id).reduce((sum, vote) => sum + vote.points, 0); return { ...person, left: Math.max(0, 100 - spent) } })

  function changeVote(id, rawValue) { setDraft((current) => { const previous = current[id] || 0; const allowed = Math.max(0, 100 - used + previous); const next = { ...current, [id]: Math.min(Number(rawValue), allowed) }; clearTimeout(saveTimer.current); saveTimer.current = setTimeout(async () => { if (!room?.id || !me?.id || removed || hydratingRef.current) return; setSaving(true); const result = await supabase.from('votes').upsert(suggestions.map((item) => ({ room_id: room.id, participant_id: me.id, suggestion_id: item.id, points: next[item.id] || 0 })), { onConflict: 'participant_id,suggestion_id' }); if (result.error) setError(result.error.message); else await refresh(room.id); setSaving(false) }, 220); return next }) }
  async function confirmKick() { if (!kickTarget || !room?.id || !me?.id) return; const target = kickTarget; setKicking(true); const kick = await supabase.from('kicks').insert({ room_id: room.id, participant_id: target.id }); if (kick.error) setError(kick.error.message); else { setParticipants((current) => current.filter((item) => item.id !== target.id)); setVotes((current) => current.filter((vote) => vote.participant_id !== target.id)); const del = await supabase.from('participants').delete().eq('id', target.id).eq('room_id', room.id); if (del.error) { setError(del.error.message); await refresh(room.id) } else await supabase.from('messages').insert({ room_id: room.id, participant_id: me.id, type: 'system', body: '', meta: { kind: 'participant-removed', actor: me.display_name, target: target.display_name } }) } setKicking(false); setKickTarget(null) }
  async function addSuggestion(event) { event.preventDefault(); const name = suggestion.trim(); if (!name || !me) return; if (name.length > 100) return setError('Suggestion must be 100 characters or fewer.'); const result = await supabase.from('suggestions').insert({ room_id: room.id, participant_id: me.id, name }); if (result.error) setError(result.error.message); else { setSuggestion(''); await supabase.from('messages').insert({ room_id: room.id, participant_id: me.id, type: 'system', body: '', meta: { kind: 'suggestion-added', actor: me.display_name, venue: name } }) } }
  async function deleteSuggestion(item) { const result = await supabase.from('suggestions').delete().eq('id', item.id); if (result.error) setError(result.error.message); else await supabase.from('messages').insert({ room_id: room.id, participant_id: me.id, type: 'system', body: '', meta: { kind: 'suggestion-removed', actor: me.display_name, venue: item.name } }) }
  async function sendChat(event) { event.preventDefault(); const body = chat.trim(); if (!body) return; setChat(''); await supabase.from('messages').insert({ room_id: room.id, participant_id: me.id, type: 'chat', body, meta: { display_name: me.display_name, participant_id: me.id } }) }
  function renderMessage(item) { const meta = item.meta || {}; const color = colored.find((person) => person.id === (item.participant_id || meta.participant_id))?.color?.solid; const style = color ? { borderLeft: `3px solid ${color}` } : undefined; if (item.type === 'chat') return <div style={style}><span className="chat-name" style={color ? { color } : undefined}>{meta.display_name}:</span> <span className="chat-body">{item.body}</span></div>; if (meta.kind === 'join') return <div style={style}><span className="chat-body"><strong>{meta.name}</strong> joined</span></div>; if (meta.kind === 'participant-removed') return <div style={style}><span className="chat-body"><strong>{meta.actor}</strong> kicked <strong>{meta.target}</strong></span></div>; if (meta.kind === 'suggestion-added') return <div style={style}><span className="chat-body"><strong>{meta.actor}</strong> added <strong>{meta.venue}</strong></span></div>; if (meta.kind === 'suggestion-removed') return <div style={style}><span className="chat-body"><strong>{meta.actor}</strong> removed <strong>{meta.venue}</strong></span></div>; return <div style={style}><span className="chat-body">{item.body}</span></div> }
  async function copyLink() { await navigator.clipboard.writeText(`${window.location.origin}/room/${upper}`); setCopyMessage('Link Copied'); window.setTimeout(() => setCopyMessage(''), 1400) }

  if (loading) return <Layout><div className="app-shell"><div className="card room-card"><h2>Loading room...</h2></div></div></Layout>
  if (error === 'Room not found.') return <Layout><div className="app-shell"><div className="card room-card"><Link to="/">Back</Link><h2>Couldn’t open room</h2><p className="error-text">{error}</p></div></div></Layout>
  return <Layout><div className="app-shell"><div className="card room-card"><div className="room-topbar"><Link to="/" className="back-link">Back</Link><div className="room-id-wrap"><span className="room-id-label">ROOM ID</span><span className="room-pill"><strong>{upper}</strong></span><button className="copy-link-btn" type="button" onClick={copyLink}>🔗 {copyMessage || 'Copy link'}</button></div></div><div className="room-stack">
    <section className="panel panel-wide"><p className="eyebrow">Live rankings</p><div className="rank-chart">{top.length ? top.map((item, index) => { const total = totals[item.id] || 0; return <div className="rank-row" key={item.id}><div className="rank-head"><span className="rank-index">{index + 1}</span><span className="rank-name">{shorten(item.name)}</span><span className="rank-total">{total}</span></div><div className="rank-track"><div className="rank-stack" style={{ width: `${(total / maxTotal) * 100}%` }}>{optimistic.filter((vote) => vote.suggestion_id === item.id && vote.points > 0).map((vote, i) => { const color = colored.find((person) => person.id === vote.participant_id)?.color || COLORS[0]; return <div className="rank-segment" key={`${vote.participant_id}-${i}`} style={{ width: `${(vote.points / total) * 100}%`, background: color.solid }} /> })}</div></div></div> }) : <div className="empty-state">No ranking yet. Add suggestions to see the leaderboard.</div>}</div><div className="points-left-block"><p className="eyebrow">Points left</p><div className="points-left-list">{pointsLeft.map((person) => <button type="button" className="points-left-row" key={person.id} disabled={person.id === me?.id || removed || kicking} onClick={() => person.id !== me?.id && setKickTarget(person)} style={{ '--user-color': person.color.solid, '--user-soft': person.color.soft, '--left-pct': `${person.left}%` }}><span className="points-left-user"><span className="person-dot" style={{ background: person.color.solid }} /><span className="points-left-name">{shorten(person.display_name, 28)}{person.id === me?.id ? ' (you)' : ''}</span></span><span className="points-left-value">{person.left}</span></button>)}</div></div></section>
    <section className="panel compact-panel"><p className="eyebrow">Live chat</p><div className="chat-log" ref={chatRef}>{messages.length ? messages.map((item) => <div className={`chat-item chat-${item.type}`} key={item.id}>{renderMessage(item)}</div>) : <div className="chat-empty">No updates yet.</div>}</div><form className="chat-form" onSubmit={sendChat}><input className="input" value={chat} onChange={(event) => setChat(event.target.value)} placeholder="Send a message" maxLength={240} /><button className="btn btn-primary" type="submit">Send</button></form></section>
    <section className="panel panel-wide voting-panel"><p className="eyebrow voting-title">Voting</p><form className="stack-form add-form" onSubmit={addSuggestion}><div className="join-row"><input className="input" value={suggestion} onChange={(event) => setSuggestion(event.target.value.slice(0, 100))} maxLength={100} placeholder="Add a suggestion (e.g. Eat at Shake Shack)" /><button className="btn btn-primary" type="submit">Add</button></div></form>{error ? <p className="error-text">{error}</p> : null}<div className="suggestion-list">{suggestions.map((item) => { const mine = draft[item.id] ?? 0; const total = totals[item.id] || 0; const maxAllowed = Math.max(0, 100 - used + mine); return <div className="suggestion-card" key={item.id}><div className="suggestion-main"><div className="suggestion-copy"><h3>{shorten(item.name)}</h3><p className="suggestion-meta">Total {total} points · Yours {mine}</p></div><div className="suggestion-actions"><div className="pill-total">{total}</div><button type="button" className="btn btn-delete" onClick={() => deleteSuggestion(item)}>Delete</button></div></div><div className="slider-block"><div className="slider-labels"><span>0</span><span>Your points {mine}</span><span>100</span></div><input type="range" className="vote-slider" min="0" max="100" value={mine} onChange={(event) => changeVote(item.id, event.target.value)} style={{ '--slider-color': meColor.solid, '--slider-soft': meColor.soft, background: `linear-gradient(to right, ${meColor.soft} 0, ${meColor.solid} ${mine}%, var(--surface-2) ${mine}%, var(--surface-2) 100%)` }} /><p className="suggestion-meta">Max you can set now: {maxAllowed}</p></div></div> })}</div></section>
  </div>{removed ? <div className="modal-backdrop"><div className="modal-card"><p className="eyebrow">Session ended</p><h3>You have been removed from this session</h3><p className="subtext small">You will be redirected to the main page in 5 seconds.</p><div className="modal-actions"><button className="btn btn-primary" type="button" onClick={() => navigate('/')}>Return now</button></div></div></div> : null}{kickTarget ? <div className="modal-backdrop"><div className="modal-card kick-modal"><p className="eyebrow">Remove participant</p><h3>Kick user?</h3><p className="subtext small">Are you sure you want to kick <strong>{kickTarget.display_name}</strong> from this session?</p><div className="modal-actions"><button className="btn btn-secondary" type="button" onClick={() => setKickTarget(null)}>Cancel</button><button className="btn btn-delete" type="button" onClick={confirmKick} disabled={kicking}>{kicking ? 'Kicking...' : 'Kick user'}</button></div></div></div> : null}</div></div></Layout>
}

export default function App() { return <Routes><Route path="/" element={<HomePage />} /><Route path="/room/:code/name" element={<NamePage />} /><Route path="/room/:code" element={<RoomPage />} /></Routes> }
